version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    # Allow PRs for major version updates but label them so they can be reviewed carefully
    labels:
      - "dependencies"
      - "automerge:disabled"
